PRODUCT_PACKAGES += \
                libhanlouis \
                libhanbrailleinput \
                libhancellout \
                libhanlcdout

# for Braille
PRODUCT_COPY_FILES += \
    device/samsung/h532b/proprietary/braille/tables/afr-za-g1.ctb:system/vendor/braille/tables/afr-za-g1.ctb	\
    device/samsung/h532b/proprietary/braille/tables/ar-ar-g1.utb:system/vendor/braille/tables/ar-ar-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/ar-fa.utb:system/vendor/braille/tables/ar-fa.utb \
    device/samsung/h532b/proprietary/braille/tables/as-in-g1.utb:system/vendor/braille/tables/as-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/aw-in-g1.utb:system/vendor/braille/tables/aw-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/be-in-g1.utb:system/vendor/braille/tables/be-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/bengali.cti:system/vendor/braille/tables/bengali.cti \
    device/samsung/h532b/proprietary/braille/tables/bg.ctb:system/vendor/braille/tables/bg.ctb \
    device/samsung/h532b/proprietary/braille/tables/bh.ctb:system/vendor/braille/tables/bh.ctb \
    device/samsung/h532b/proprietary/braille/tables/bo.ctb:system/vendor/braille/tables/bo.ctb \
    device/samsung/h532b/proprietary/braille/tables/boxes.ctb:system/vendor/braille/tables/boxes.ctb \
    device/samsung/h532b/proprietary/braille/tables/br-in-g1.utb:system/vendor/braille/tables/br-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/braille-patterns.cti:system/vendor/braille/tables/braille-patterns.cti \
    device/samsung/h532b/proprietary/braille/tables/ca-chardefs.cti:system/vendor/braille/tables/ca-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/ca-g1.ctb:system/vendor/braille/tables/ca-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/chardefs.cti:system/vendor/braille/tables/chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/chr-us-g1.ctb:system/vendor/braille/tables/chr-us-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/ckb-chardefs.cti:system/vendor/braille/tables/ckb-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/ckb-g1.ctb:system/vendor/braille/tables/ckb-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/ckb-translation.cti:system/vendor/braille/tables/ckb-translation.cti \
    device/samsung/h532b/proprietary/braille/tables/compress.cti:system/vendor/braille/tables/compress.cti \
    device/samsung/h532b/proprietary/braille/tables/controlchars.cti:system/vendor/braille/tables/controlchars.cti \
    device/samsung/h532b/proprietary/braille/tables/corrections.cti:system/vendor/braille/tables/corrections.cti \
    device/samsung/h532b/proprietary/braille/tables/countries.cti:system/vendor/braille/tables/countries.cti \
    device/samsung/h532b/proprietary/braille/tables/cs-chardefs.cti:system/vendor/braille/tables/cs-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/cs-g1.ctb:system/vendor/braille/tables/cs-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/cs-translation.cti:system/vendor/braille/tables/cs-translation.cti \
    device/samsung/h532b/proprietary/braille/tables/cy-cy-g1.utb:system/vendor/braille/tables/cy-cy-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/cy-cy-g2.ctb:system/vendor/braille/tables/cy-cy-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/Cz-Cz-g1.utb:system/vendor/braille/tables/Cz-Cz-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/da-ansi8.dis:system/vendor/braille/tables/da-ansi8.dis \
    device/samsung/h532b/proprietary/braille/tables/da-chardefs6.cti:system/vendor/braille/tables/da-chardefs6.cti \
    device/samsung/h532b/proprietary/braille/tables/da-chardefs8.cti:system/vendor/braille/tables/da-chardefs8.cti \
    device/samsung/h532b/proprietary/braille/tables/da-dk-common6.uti:system/vendor/braille/tables/da-dk-common6.uti \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g16.utb:system/vendor/braille/tables/da-dk-g16.utb \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g18.utb:system/vendor/braille/tables/da-dk-g18.utb \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g26-patches.cti:system/vendor/braille/tables/da-dk-g26-patches.cti \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g26.ctb:system/vendor/braille/tables/da-dk-g26.ctb \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g28-patches.cti:system/vendor/braille/tables/da-dk-g28-patches.cti \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g28.ctb:system/vendor/braille/tables/da-dk-g28.ctb \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g28caps.cti:system/vendor/braille/tables/da-dk-g28caps.cti \
    device/samsung/h532b/proprietary/braille/tables/da-dk-g2core.cti:system/vendor/braille/tables/da-dk-g2core.cti \
    device/samsung/h532b/proprietary/braille/tables/da-dk-nocaps.uti:system/vendor/braille/tables/da-dk-nocaps.uti \
    device/samsung/h532b/proprietary/braille/tables/da-dk.dis:system/vendor/braille/tables/da-dk.dis \
    device/samsung/h532b/proprietary/braille/tables/da-lt.ctb:system/vendor/braille/tables/da-lt.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-ch-accents.cti:system/vendor/braille/tables/de-ch-accents.cti \
    device/samsung/h532b/proprietary/braille/tables/de-ch-g0.utb:system/vendor/braille/tables/de-ch-g0.utb \
    device/samsung/h532b/proprietary/braille/tables/de-ch-g1.ctb:system/vendor/braille/tables/de-ch-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-ch-g2.ctb:system/vendor/braille/tables/de-ch-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-chardefs6.cti:system/vendor/braille/tables/de-chardefs6.cti \
    device/samsung/h532b/proprietary/braille/tables/de-chardefs8.cti:system/vendor/braille/tables/de-chardefs8.cti \
    device/samsung/h532b/proprietary/braille/tables/de-chess.ctb:system/vendor/braille/tables/de-chess.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-de-accents.cti:system/vendor/braille/tables/de-de-accents.cti \
    device/samsung/h532b/proprietary/braille/tables/de-de-comp8.ctb:system/vendor/braille/tables/de-de-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-de-g0.utb:system/vendor/braille/tables/de-de-g0.utb \
    device/samsung/h532b/proprietary/braille/tables/de-de-g1.ctb:system/vendor/braille/tables/de-de-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-de-g2.ctb:system/vendor/braille/tables/de-de-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/de-de.dis:system/vendor/braille/tables/de-de.dis \
    device/samsung/h532b/proprietary/braille/tables/de-eurobrl6.dis:system/vendor/braille/tables/de-eurobrl6.dis \
    device/samsung/h532b/proprietary/braille/tables/de-eurobrl6u.dis:system/vendor/braille/tables/de-eurobrl6u.dis \
    device/samsung/h532b/proprietary/braille/tables/de-g0-core.uti:system/vendor/braille/tables/de-g0-core.uti \
    device/samsung/h532b/proprietary/braille/tables/de-g1-core.cti:system/vendor/braille/tables/de-g1-core.cti \
    device/samsung/h532b/proprietary/braille/tables/de-g2-core.cti:system/vendor/braille/tables/de-g2-core.cti \
    device/samsung/h532b/proprietary/braille/tables/devanagari.cti:system/vendor/braille/tables/devanagari.cti \
    device/samsung/h532b/proprietary/braille/tables/digits6Dots.uti:system/vendor/braille/tables/digits6Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/digits6DotsPlusDot6.uti:system/vendor/braille/tables/digits6DotsPlusDot6.uti \
    device/samsung/h532b/proprietary/braille/tables/digits8Dots.uti:system/vendor/braille/tables/digits8Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/dra.ctb:system/vendor/braille/tables/dra.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-chess.ctb:system/vendor/braille/tables/en-chess.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-gb-comp8.ctb:system/vendor/braille/tables/en-gb-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-gb-g1.utb:system/vendor/braille/tables/en-gb-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/en-GB-g2.ctb:system/vendor/braille/tables/en-GB-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-in-g1.ctb:system/vendor/braille/tables/en-in-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-ueb-chardefs.uti:system/vendor/braille/tables/en-ueb-chardefs.uti \
    device/samsung/h532b/proprietary/braille/tables/en-ueb-g1.ctb:system/vendor/braille/tables/en-ueb-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-ueb-g2.ctb:system/vendor/braille/tables/en-ueb-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-brf.dis:system/vendor/braille/tables/en-us-brf.dis \
    device/samsung/h532b/proprietary/braille/tables/en-us-comp6.ctb:system/vendor/braille/tables/en-us-comp6.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-comp8.ctb:system/vendor/braille/tables/en-us-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-compbrl.ctb:system/vendor/braille/tables/en-us-compbrl.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-g1.ctb:system/vendor/braille/tables/en-us-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-g2.ctb:system/vendor/braille/tables/en-us-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-interline.ctb:system/vendor/braille/tables/en-us-interline.ctb \
    device/samsung/h532b/proprietary/braille/tables/en-us-mathtext.ctb:system/vendor/braille/tables/en-us-mathtext.ctb \
    device/samsung/h532b/proprietary/braille/tables/en_CA.ctb:system/vendor/braille/tables/en_CA.ctb \
    device/samsung/h532b/proprietary/braille/tables/eo-g1-x-system.ctb:system/vendor/braille/tables/eo-g1-x-system.ctb \
    device/samsung/h532b/proprietary/braille/tables/eo-g1.ctb:system/vendor/braille/tables/eo-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/es-chardefs.cti:system/vendor/braille/tables/es-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/Es-Es-G0.utb:system/vendor/braille/tables/Es-Es-G0.utb \
    device/samsung/h532b/proprietary/braille/tables/Es-Es-g1.utb:system/vendor/braille/tables/Es-Es-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/es-g1.ctb:system/vendor/braille/tables/es-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/es-new.dis:system/vendor/braille/tables/es-new.dis \
    device/samsung/h532b/proprietary/braille/tables/es-old.dis:system/vendor/braille/tables/es-old.dis \
    device/samsung/h532b/proprietary/braille/tables/es-translation.cti:system/vendor/braille/tables/es-translation.cti \
    device/samsung/h532b/proprietary/braille/tables/et-g0.utb:system/vendor/braille/tables/et-g0.utb \
    device/samsung/h532b/proprietary/braille/tables/et.ctb:system/vendor/braille/tables/et.ctb \
    device/samsung/h532b/proprietary/braille/tables/ethio-g1.ctb:system/vendor/braille/tables/ethio-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/eurodefs.cti:system/vendor/braille/tables/eurodefs.cti \
    device/samsung/h532b/proprietary/braille/tables/fi-fi-8dot.ctb:system/vendor/braille/tables/fi-fi-8dot.ctb \
    device/samsung/h532b/proprietary/braille/tables/fi-fi.ctb:system/vendor/braille/tables/fi-fi.ctb \
    device/samsung/h532b/proprietary/braille/tables/fi.utb:system/vendor/braille/tables/fi.utb \
    device/samsung/h532b/proprietary/braille/tables/fi1.ctb:system/vendor/braille/tables/fi1.ctb \
    device/samsung/h532b/proprietary/braille/tables/fi2.ctb:system/vendor/braille/tables/fi2.ctb \
    device/samsung/h532b/proprietary/braille/tables/fr-2007.ctb:system/vendor/braille/tables/fr-2007.ctb \
    device/samsung/h532b/proprietary/braille/tables/fr-bfu-comp6.utb:system/vendor/braille/tables/fr-bfu-comp6.utb \
    device/samsung/h532b/proprietary/braille/tables/fr-bfu-comp8.utb:system/vendor/braille/tables/fr-bfu-comp8.utb \
    device/samsung/h532b/proprietary/braille/tables/fr-bfu-g2.ctb:system/vendor/braille/tables/fr-bfu-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/fr-ca-g1.utb:system/vendor/braille/tables/fr-ca-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/Fr-Ca-g2.ctb:system/vendor/braille/tables/Fr-Ca-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/fr-fr-g1.utb:system/vendor/braille/tables/fr-fr-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/Fr-Fr-g2.ctb:system/vendor/braille/tables/Fr-Fr-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/ga-g1.utb:system/vendor/braille/tables/ga-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/ga-g2.ctb:system/vendor/braille/tables/ga-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/gd.ctb:system/vendor/braille/tables/gd.ctb \
    device/samsung/h532b/proprietary/braille/tables/gon.ctb:system/vendor/braille/tables/gon.ctb \
    device/samsung/h532b/proprietary/braille/tables/gr-bb.ctb:system/vendor/braille/tables/gr-bb.ctb \
    device/samsung/h532b/proprietary/braille/tables/gr-gr-g1.utb:system/vendor/braille/tables/gr-gr-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/gu-in-g1.utb:system/vendor/braille/tables/gu-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/gujarati.cti:system/vendor/braille/tables/gujarati.cti \
    device/samsung/h532b/proprietary/braille/tables/gurumuki.cti:system/vendor/braille/tables/gurumuki.cti \
    device/samsung/h532b/proprietary/braille/tables/haw-us-g1.ctb:system/vendor/braille/tables/haw-us-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/he.ctb:system/vendor/braille/tables/he.ctb \
    device/samsung/h532b/proprietary/braille/tables/hi-in-g1.utb:system/vendor/braille/tables/hi-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/hr.ctb:system/vendor/braille/tables/hr.ctb \
    device/samsung/h532b/proprietary/braille/tables/hu-backtranslate-correction.dis:system/vendor/braille/tables/hu-backtranslate-correction.dis \
    device/samsung/h532b/proprietary/braille/tables/hu-chardefs.cti:system/vendor/braille/tables/hu-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/hu-exceptionwords.cti:system/vendor/braille/tables/hu-exceptionwords.cti \
    device/samsung/h532b/proprietary/braille/tables/hu-hu-comp8.ctb:system/vendor/braille/tables/hu-hu-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/hu-hu-g1.ctb:system/vendor/braille/tables/hu-hu-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/hy.ctb:system/vendor/braille/tables/hy.ctb \
    device/samsung/h532b/proprietary/braille/tables/hyph_cs_CZ.dic:system/vendor/braille/tables/hyph_cs_CZ.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_da_DK.dic:system/vendor/braille/tables/hyph_da_DK.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_de_DE.dic:system/vendor/braille/tables/hyph_de_DE.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_en_US.dic:system/vendor/braille/tables/hyph_en_US.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_eo.dic:system/vendor/braille/tables/hyph_eo.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_es_ES.dic:system/vendor/braille/tables/hyph_es_ES.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_fr_FR.dic:system/vendor/braille/tables/hyph_fr_FR.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_hu_HU.dic:system/vendor/braille/tables/hyph_hu_HU.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_it_IT.dic:system/vendor/braille/tables/hyph_it_IT.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_nb_NO.dic:system/vendor/braille/tables/hyph_nb_NO.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_nl_NL.dic:system/vendor/braille/tables/hyph_nl_NL.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_nn_NO.dic:system/vendor/braille/tables/hyph_nn_NO.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_pl_PL.dic:system/vendor/braille/tables/hyph_pl_PL.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_pt_PT.dic:system/vendor/braille/tables/hyph_pt_PT.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_ru.dic:system/vendor/braille/tables/hyph_ru.dic \
    device/samsung/h532b/proprietary/braille/tables/hyph_sv_SE.dic:system/vendor/braille/tables/hyph_sv_SE.dic \
    device/samsung/h532b/proprietary/braille/tables/is-chardefs6.cti:system/vendor/braille/tables/is-chardefs6.cti \
    device/samsung/h532b/proprietary/braille/tables/is-chardefs8.cti:system/vendor/braille/tables/is-chardefs8.cti \
    device/samsung/h532b/proprietary/braille/tables/is.ctb:system/vendor/braille/tables/is.ctb \
    device/samsung/h532b/proprietary/braille/tables/it-it-comp6.utb:system/vendor/braille/tables/it-it-comp6.utb \
    device/samsung/h532b/proprietary/braille/tables/it-it-comp8.utb:system/vendor/braille/tables/it-it-comp8.utb \
    device/samsung/h532b/proprietary/braille/tables/iu-ca-g1.ctb:system/vendor/braille/tables/iu-ca-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/ka-in-g1.utb:system/vendor/braille/tables/ka-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/kannada.cti:system/vendor/braille/tables/kannada.cti \
    device/samsung/h532b/proprietary/braille/tables/kh-in-g1.utb:system/vendor/braille/tables/kh-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/ko-2006-g1.ctb:system/vendor/braille/tables/ko-2006-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/ko-2006-g2.ctb:system/vendor/braille/tables/ko-2006-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/ko-2006.cti:system/vendor/braille/tables/ko-2006.cti \
    device/samsung/h532b/proprietary/braille/tables/ko-chars.cti:system/vendor/braille/tables/ko-chars.cti \
    device/samsung/h532b/proprietary/braille/tables/ko-g1-rules.cti:system/vendor/braille/tables/ko-g1-rules.cti \
    device/samsung/h532b/proprietary/braille/tables/ko-g1.ctb:system/vendor/braille/tables/ko-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/ko-g2-rules.cti:system/vendor/braille/tables/ko-g2-rules.cti \
    device/samsung/h532b/proprietary/braille/tables/ko-g2.ctb:system/vendor/braille/tables/ko-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/ko.cti:system/vendor/braille/tables/ko.cti \
    device/samsung/h532b/proprietary/braille/tables/kok.ctb:system/vendor/braille/tables/kok.ctb \
    device/samsung/h532b/proprietary/braille/tables/kru.ctb:system/vendor/braille/tables/kru.ctb \
    device/samsung/h532b/proprietary/braille/tables/ks-in-g1.utb:system/vendor/braille/tables/ks-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/latinLetterDef6Dots.uti:system/vendor/braille/tables/latinLetterDef6Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/latinLetterDef8Dots.uti:system/vendor/braille/tables/latinLetterDef8Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/litdigits6Dots.uti:system/vendor/braille/tables/litdigits6Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/loweredDigits6Dots.uti:system/vendor/braille/tables/loweredDigits6Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/loweredDigits8Dots.uti:system/vendor/braille/tables/loweredDigits8Dots.uti \
    device/samsung/h532b/proprietary/braille/tables/lt.ctb:system/vendor/braille/tables/lt.ctb \
    device/samsung/h532b/proprietary/braille/tables/Lv-Lv-g1.utb:system/vendor/braille/tables/Lv-Lv-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/Makefile:system/vendor/braille/tables/Makefile \
    device/samsung/h532b/proprietary/braille/tables/Makefile.am:system/vendor/braille/tables/Makefile.am \
    device/samsung/h532b/proprietary/braille/tables/Makefile.in:system/vendor/braille/tables/Makefile.in \
    device/samsung/h532b/proprietary/braille/tables/malayalam.cti:system/vendor/braille/tables/malayalam.cti \
    device/samsung/h532b/proprietary/braille/tables/mao-nz-g1.ctb:system/vendor/braille/tables/mao-nz-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/marburg.ctb:system/vendor/braille/tables/marburg.ctb \
    device/samsung/h532b/proprietary/braille/tables/marburg_edit.ctb:system/vendor/braille/tables/marburg_edit.ctb \
    device/samsung/h532b/proprietary/braille/tables/marburg_single_cell_defs.cti:system/vendor/braille/tables/marburg_single_cell_defs.cti \
    device/samsung/h532b/proprietary/braille/tables/marburg_unicode_defs.cti:system/vendor/braille/tables/marburg_unicode_defs.cti \
    device/samsung/h532b/proprietary/braille/tables/ml-in-g1.utb:system/vendor/braille/tables/ml-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/mn-in-g1.utb:system/vendor/braille/tables/mn-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/mr-in-g1.utb:system/vendor/braille/tables/mr-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/mt.ctb:system/vendor/braille/tables/mt.ctb \
    device/samsung/h532b/proprietary/braille/tables/mun.ctb:system/vendor/braille/tables/mun.ctb \
    device/samsung/h532b/proprietary/braille/tables/mwr.ctb:system/vendor/braille/tables/mwr.ctb \
    device/samsung/h532b/proprietary/braille/tables/ne.ctb:system/vendor/braille/tables/ne.ctb \
    device/samsung/h532b/proprietary/braille/tables/nemeth.ctb:system/vendor/braille/tables/nemeth.ctb \
    device/samsung/h532b/proprietary/braille/tables/nemethdefs.cti:system/vendor/braille/tables/nemethdefs.cti \
    device/samsung/h532b/proprietary/braille/tables/nemeth_edit.ctb:system/vendor/braille/tables/nemeth_edit.ctb \
    device/samsung/h532b/proprietary/braille/tables/nl-BE-chardefs.cti:system/vendor/braille/tables/nl-BE-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/nl-BE-g1.ctb:system/vendor/braille/tables/nl-BE-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/nl-BE.dis:system/vendor/braille/tables/nl-BE.dis \
    device/samsung/h532b/proprietary/braille/tables/nl-NL-chardefs.cti:system/vendor/braille/tables/nl-NL-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/nl-NL-g1.ctb:system/vendor/braille/tables/nl-NL-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/no-no-g0.utb:system/vendor/braille/tables/no-no-g0.utb \
    device/samsung/h532b/proprietary/braille/tables/no-no-g1.ctb:system/vendor/braille/tables/no-no-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/no-no-g2.ctb:system/vendor/braille/tables/no-no-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/no-no-g3.ctb:system/vendor/braille/tables/no-no-g3.ctb \
    device/samsung/h532b/proprietary/braille/tables/no-no-generic.ctb:system/vendor/braille/tables/no-no-generic.ctb \
    device/samsung/h532b/proprietary/braille/tables/no-no-generic.dis:system/vendor/braille/tables/no-no-generic.dis \
    device/samsung/h532b/proprietary/braille/tables/no-no.ctb:system/vendor/braille/tables/no-no.ctb \
    device/samsung/h532b/proprietary/braille/tables/no-no.dis:system/vendor/braille/tables/no-no.dis \
    device/samsung/h532b/proprietary/braille/tables/np-in-g1.utb:system/vendor/braille/tables/np-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/or-in-g1.utb:system/vendor/braille/tables/or-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/oriya.cti:system/vendor/braille/tables/oriya.cti \
    device/samsung/h532b/proprietary/braille/tables/pi.ctb:system/vendor/braille/tables/pi.ctb \
    device/samsung/h532b/proprietary/braille/tables/pl-pl-comp8.ctb:system/vendor/braille/tables/pl-pl-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/Pl-Pl-g1.utb:system/vendor/braille/tables/Pl-Pl-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/printables.cti:system/vendor/braille/tables/printables.cti \
    device/samsung/h532b/proprietary/braille/tables/pt-pt-comp8.ctb:system/vendor/braille/tables/pt-pt-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/pt-pt-g1.utb:system/vendor/braille/tables/pt-pt-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/pt-pt-g2.ctb:system/vendor/braille/tables/pt-pt-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/pu-in-g1.utb:system/vendor/braille/tables/pu-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/README:system/vendor/braille/tables/README \
    device/samsung/h532b/proprietary/braille/tables/ro.ctb:system/vendor/braille/tables/ro.ctb \
    device/samsung/h532b/proprietary/braille/tables/ru-chardefs.cti:system/vendor/braille/tables/ru-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/ru-compbrl.ctb:system/vendor/braille/tables/ru-compbrl.ctb \
    device/samsung/h532b/proprietary/braille/tables/ru-letters.dis:system/vendor/braille/tables/ru-letters.dis \
    device/samsung/h532b/proprietary/braille/tables/ru-litbrl.ctb:system/vendor/braille/tables/ru-litbrl.ctb \
    device/samsung/h532b/proprietary/braille/tables/ru-ru-g1.utb:system/vendor/braille/tables/ru-ru-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/ru-ru.dis:system/vendor/braille/tables/ru-ru.dis \
    device/samsung/h532b/proprietary/braille/tables/ru.ctb:system/vendor/braille/tables/ru.ctb \
    device/samsung/h532b/proprietary/braille/tables/sa-in-g1.utb:system/vendor/braille/tables/sa-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/Se-Se-g1.utb:system/vendor/braille/tables/Se-Se-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/se-se.ctb:system/vendor/braille/tables/se-se.ctb \
    device/samsung/h532b/proprietary/braille/tables/se-se.dis:system/vendor/braille/tables/se-se.dis \
    device/samsung/h532b/proprietary/braille/tables/si-in-g1.utb:system/vendor/braille/tables/si-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/sk-sk-g1.utb:system/vendor/braille/tables/sk-sk-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/sk-sk.utb:system/vendor/braille/tables/sk-sk.utb \
    device/samsung/h532b/proprietary/braille/tables/sl-si-comp8.ctb:system/vendor/braille/tables/sl-si-comp8.ctb \
    device/samsung/h532b/proprietary/braille/tables/sl-si-g1.utb:system/vendor/braille/tables/sl-si-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/sot-za-g1.ctb:system/vendor/braille/tables/sot-za-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/spaces.ctb:system/vendor/braille/tables/spaces.ctb \
    device/samsung/h532b/proprietary/braille/tables/sr-chardefs.cti:system/vendor/braille/tables/sr-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/sr-g1.ctb:system/vendor/braille/tables/sr-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/sr-translation.cti:system/vendor/braille/tables/sr-translation.cti \
    device/samsung/h532b/proprietary/braille/tables/sv-1989.ctb:system/vendor/braille/tables/sv-1989.ctb \
    device/samsung/h532b/proprietary/braille/tables/sv-1996.ctb:system/vendor/braille/tables/sv-1996.ctb \
    device/samsung/h532b/proprietary/braille/tables/ta-ta-g1.ctb:system/vendor/braille/tables/ta-ta-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/ta.ctb:system/vendor/braille/tables/ta.ctb \
    device/samsung/h532b/proprietary/braille/tables/tamil.cti:system/vendor/braille/tables/tamil.cti \
    device/samsung/h532b/proprietary/braille/tables/te-in-g1.utb:system/vendor/braille/tables/te-in-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/telugu.cti:system/vendor/braille/tables/telugu.cti \
    device/samsung/h532b/proprietary/braille/tables/text_nabcc.dis:system/vendor/braille/tables/text_nabcc.dis \
    device/samsung/h532b/proprietary/braille/tables/tr.ctb:system/vendor/braille/tables/tr.ctb \
    device/samsung/h532b/proprietary/braille/tables/tsn-za-g1.ctb:system/vendor/braille/tables/tsn-za-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/UEBC-g1.utb:system/vendor/braille/tables/UEBC-g1.utb \
    device/samsung/h532b/proprietary/braille/tables/UEBC-g2.ctb:system/vendor/braille/tables/UEBC-g2.ctb \
    device/samsung/h532b/proprietary/braille/tables/ukchardefs.cti:system/vendor/braille/tables/ukchardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/ukmaths.ctb:system/vendor/braille/tables/ukmaths.ctb \
    device/samsung/h532b/proprietary/braille/tables/ukmaths_edit.ctb:system/vendor/braille/tables/ukmaths_edit.ctb \
    device/samsung/h532b/proprietary/braille/tables/ukmaths_single_cell_defs.cti:system/vendor/braille/tables/ukmaths_single_cell_defs.cti \
    device/samsung/h532b/proprietary/braille/tables/ukmaths_unicode_defs.cti:system/vendor/braille/tables/ukmaths_unicode_defs.cti \
    device/samsung/h532b/proprietary/braille/tables/uni-text.dis:system/vendor/braille/tables/uni-text.dis \
    device/samsung/h532b/proprietary/braille/tables/unicode.dis:system/vendor/braille/tables/unicode.dis \
    device/samsung/h532b/proprietary/braille/tables/unicodedefs.cti:system/vendor/braille/tables/unicodedefs.cti \
    device/samsung/h532b/proprietary/braille/tables/us-table.dis:system/vendor/braille/tables/us-table.dis \
    device/samsung/h532b/proprietary/braille/tables/vi-g1.ctb:system/vendor/braille/tables/vi-g1.ctb \
    device/samsung/h532b/proprietary/braille/tables/vi.ctb:system/vendor/braille/tables/vi.ctb \
    device/samsung/h532b/proprietary/braille/tables/wiskunde-chardefs.cti:system/vendor/braille/tables/wiskunde-chardefs.cti \
    device/samsung/h532b/proprietary/braille/tables/wiskunde-translation.cti:system/vendor/braille/tables/wiskunde-translation.cti \
    device/samsung/h532b/proprietary/braille/tables/wiskunde.ctb:system/vendor/braille/tables/wiskunde.ctb \
    device/samsung/h532b/proprietary/braille/tables/zh-hk.ctb:system/vendor/braille/tables/zh-hk.ctb \
    device/samsung/h532b/proprietary/braille/tables/zh-tw.ctb:system/vendor/braille/tables/zh-tw.ctb

    
